<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter field">
    <label class="sorter-label label" for="sorter"><?php echo __('Sort By') ?></label>
    <div class="control">
        <select id="sorter" data-role="sorter" class="sorter-options" data-mage-init='{"selectize":{}}'>
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <option value="<?php echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php echo __('Asc') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php echo __('Desc') ?></span>
        </a>
    <?php endif; ?>
</div>
