<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\AbstractProduct
*/
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>


<?php if ($exist):?>
    <?php //if ($type == 'related' || $type == 'upsell'): ?>
    	<div class="items-block items-block-<?php echo $class; ?>">
            <?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
            <?php echo $block->getHeight() ?>
    		<span class="items-block-heading heading-<?php echo $class?>"><?php echo $title; ?></span>
			<amp-carousel height="400" width="300" layout="responsive" type="slides" autoplay controls delay="5000">
				<?php foreach ($items as $_item) : ?>
                    <?php
                    	/**
                    	 * Get product data
                    	 */
                        $_productName = $block->escapeHtml($_item->getName());
                        $_productUrl = $block->getProductUrl($_item);

                        /**
                         * Get product image and set amp-image template
                         */
                        $_productImage = $block->getImage($_item, 'product_page_image_medium');
                        $_productImage->setCustomAttributes('layout="responsive"');
                        $_productImage->setTemplate('Zemez_Amp::catalog/product/image.phtml');
                    ?>
                    <div class="item-content">
						<a class="item-image" href="<?php echo $_productUrl ?>" title="<?php echo $_productName ?></a>">
                            <?php echo $_productImage->toHtml() ?>
                        </a>
                        <a class="item-detail" href="<?php echo $_productUrl ?>" title="<?php echo $_productName ?></a>">
                            <span class="item-name"><?php echo $_productName ?></span>
                            <span class="item-price"><?php echo $block->getProductPrice($_item); ?></span>
                        </a>
                    </div>
				<?php endforeach; ?>
			</amp-carousel>
    	</div>
    <?php //endif; ?>
<?php endif; ?>
