<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar amp-toolbar-products">

        <?php // include ($block->getTemplateFile('Zemez_Amp::catalog/product/list/toolbar/amount.phtml')) ?>

        <?php // echo $block->getPagerHtml() ?>

        <?php // include ($block->getTemplateFile('Zemez_Amp::catalog/product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Zemez_Amp::catalog/product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
<?php endif ?>
