<?php
/** @var $block TemplateMonster\NewsletterPopup\Block\Styles */
$helper = $block->getHelper();
?>
.modal-popup .modal-inner-wrap {
    pointer-events: auto;
}
<?php if ($helper->getPopupWidth()): ?>
.modal-popup.newsletter-popup .modal-inner-wrap {
    width: <?php echo $helper->getPopupWidth() ?>px;
}
<?php endif; ?>
.modal-popup.newsletter-popup .buttons-container button.subscribe {
    background-color: <?php echo $helper->getButtonColor() ?>;
    border-color: <?php echo $helper->getButtonColor() ?>;
}
.modal-popup.newsletter-popup .buttons-container button.subscribe:hover {
    background-color: <?php echo $helper->getButtonHoverColor() ?>;
    border-color: <?php echo $helper->getButtonHoverColor() ?>;
}
.modal-popup .modal-social {
    font-size: 1.75em;
}
.modal-popup .modal-social .fa {
    padding: 7px 5px;
}
.modal-popup .modal-social :link,
.modal-popup .modal-social :hover {
    text-decoration: none;
}
<?php foreach ($helper->getAvailableIcons() as $icon): ?>
.modal-popup .modal-social .fa-<?php echo $icon ?> {
    color: <?php echo $helper->getIconColor($icon) ?: '#000' ?>;
    background-color: <?php echo $helper->getIconBackground($icon) ?: '#fff' ?>;
}
.modal-popup .modal-social .fa-<?php echo $icon ?>:hover,
.modal-popup .modal-social .fa-<?php echo $icon ?>:active {
    color: <?php echo $helper->getIconHoverColor($icon) ?: '#000' ?>;
    background-color: <?php echo $helper->getIconBackgroundHover($icon) ?: '#fff' ?>;
}
<?php endforeach; ?>
