<?php if(!$this->isCompatible()):?>
    <div>
        <h1>NOTICE:</h1>
        <p>For WeltPixel Lazy Loading extension to work with OwlCarouselSlider extension, please do the following steps:</p>
        <ul style="list-style-type: none">
            <li>1. download patch module from <a href="<?= $this->getDownloadLink()?>" target="_blank">HERE</a></li>
            <li>2. unzip and copy the module files in app/code/WelPixel/LazyLoadingOwlCarouselSlider</li>
            <li>3. access the root of your magento 2 project and run the following commands</li>
            <li><code>php bin/magento module:enable WeltPixel_LazyLoadingOwlCarouselSlider --clear-static-content</code></li>
            <li><code>php bin/magento setup:upgrade</code></li>
            <li>4. Flush any cache that you might still have enabled on your server or in Magento.</li>
        </ul>
    </div>
<?php endif;?>