<?php /** @var TemplateMonster\Blog\Block\Post\SocialSharing\AddThis\Icons $block */ ?>
<div class="addthis_toolbox addthis_default_style" <?php echo $block->getCustomMetadata() ?>>
    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
    <iframe allowtransparency="true" frameborder="0" scrolling="no" src="https://platform.twitter.com/widgets/tweet_button.html" style="width: 65px; height: 20px; float: left;"></iframe>
    <a class="addthis_counter addthis_pill_style" href="javascript:void(0)"></a>
</div>