<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<?php
$_helper = $this->helper('Aitoc\ReviewBooster\Helper\Data');
$reviewRatingNames = $_helper->getRatingNames();
?>
<div class="block review-add">
    <div class="block-title"><strong><?php echo __('Write Your Own Review') ?></strong></div>
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?php echo $block->getAction() ?>" class="review-form" method="post" id="review-form" enctype="multipart/form-data" data-role="product-review-form" data-bind="scope: 'review-form'">
                <?php echo $block->getBlockHtml('formkey'); ?>
                <?php echo $block->getChildHtml('form_fields_before')?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
                    <!--<legend class="legend review-legend"><span><?php echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend>-->
					<legend class="legend review-legend"><span><?php echo __("You're reviewing:"); ?> <?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></span></legend> <br />
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                            <legend class="label"><span><?php echo __('Overall rating') ?><span></legend>
                            <div class="control">
                                <div class="nested" id="product-review-table">
                                    <?php foreach ($block->getRatings() as $_rating): ?>
                                        <div class="field choice review-field-rating">
                                            <?php if(count($block->getRatings()) > 1): ?>
                                            <!--<label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>-->
                                            <?php else: ?>
                                            <!--<label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span></span></label>-->
                                            <?php endif; ?>
                                            <div class="control review-control-vote">
                                                <?php $options = $_rating->getOptions();?>
                                                <?php $iterator = 1; foreach ($options as $_option): ?>
                                                    <input
                                                        type="radio"
                                                        name="ratings[<?php echo $_rating->getId() ?>]"
                                                        id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>"
                                                        value="<?php echo $_option->getId() ?>"
                                                        class="radio"
                                                        data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                        aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>_label" />
                                                    <label
                                                        class="rating-<?php echo $iterator; ?> icon-star"
                                                        for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>"
                                                        title="<?php echo __($reviewRatingNames[$iterator]) ?>"
                                                        id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_rating->getId() ?>_<?php echo $_option->getValue() ?>_label">
                                                        <span><?php echo __($reviewRatingNames[$iterator]) ?></span>
                                                    </label>
                                                    <?php $iterator++; ?>
                                                <?php endforeach; ?>
                                                <span id="rating-name-<?php echo $_rating->getId() ?>" class="rating-name"></span>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div class="field review-field-nickname">
                        <!--<label for="nickname_field" class="label"><span><?php echo __('Name') ?></span></label>-->
                        <div class="control">
                            <input type="text" name="nickname" id="nickname_field" class="input-text" data-bind="value: nickname()" placeholder="<?php echo __('Name') ?>" />
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <!--<label for="summary_field" class="label"><span><?php echo __('Review Title*') ?></span></label>-->
                        <div class="control">
                            <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" placeholder="<?php echo __('Review Title*') ?>"/>
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <!--<label for="review_field" class="label"><span><?php echo __('Comments*') ?></span></label>-->
                        <div class="control">
                            <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail" placeholder="<?php echo __('Comments*') ?>"></textarea>
                        </div>
                    </div>
                    <!--<div class="field review-field-advantages">
                        <label for="advantages_field" class="label"><span><?php echo __('What I like about this product') ?></span></label>
                        <div class="control">
                            <input type="text" name="advantages" id="advantages_field" class="input-text" data-validate="{required:false}" data-bind="value: review().advantages" />
                        </div>
                    </div>-->
                    <!-- <div class="field review-field-disadvantages">
                        <label for="disadvantages_field" class="label"><span><?php echo __('What I don\'t like about this product') ?></span></label>
                        <div class="control">
                            <input type="text" name="disadvantages" id="disadvantages_field" class="input-text" data-validate="{required:false}" data-bind="value: review().disadvantages" />
                        </div>
                    </div>-->
                    <?php if ($_helper->getConfigCollectionByUploadImage() == 1): ?>
                        <div class="field review-field-image">
                           <!-- <label for="image_field" class="label"><span><?php echo __('Upload Image') ?></span></label>-->
                            <div class="control">
                                <input type="file" name="image" id="image_field" class="input-text"
                                       data-validate="{required:false}" data-bind="value: review().image"/>
                            </div>
                        </div>
                    <?php endif ?>
                </fieldset>
            </form>
            <script>
                require(
                    [
                        'jquery',
                        'Magento_Ui/js/modal/modal'
                    ],
                    function(
                        $,
                        modal
                    ) {
                        var options = {
                            type: 'popup',
                            responsive: true,
                            innerScroll: true,
                            title: 'Write Your Review',
                            buttons: [{
                                text: $.mage.__('Submit'),
                                class: '',
                                click: function () {
                                    $('#review-form').submit();
                                    this.closeModal();
                                }
                            }]
                        };
			            var popup = modal(options, $('.review-add'));
                        $(function(){
                            $('.review-form-actions .write-action').on('click',function(){
                                $('.review-add').modal('openModal'); 
                            });
                            $('.reviews-actions > a.add').on('click',function(event){
			        event.preventDefault();	
                                $('.review-add').modal('openModal'); 
                            });
                        });
                        
                    }
                );
            </script>
            <script>
                require([
                    "jquery",
                    "mage/mage"
                ], function($){
                    $('#review-form').mage('validation', {
                        errorPlacement: function (error, element) {
                            if (element.parents('#product-review-table').length) {
                                $('#product-review-table').siblings(this.errorElement + '.' + this.errorClass).remove();
                                $('#product-review-table').after(error);
                            } else {
                                element.after(error);
                            }
                        }
                    });
                });
            </script>
            <script>
                require([
                    "jquery"
                ], function($){
                    $(function () {
			$('.reviews-actions > a.view').on('click',function(event){
				event.preventDefault();
				console.log('view review is clicked');
				$("html, body").animate({
				 scrollTop: $('.review-list').last().offset().top },
                    			1000);
			});
                        $('#review-form')
                            .on('mouseover', '[class^="rating-"]', function (event) {
				var ratingId = this.id.split('_');
                                $('#rating-name-' + ratingId[1]).text(this.title);
				$(event.target).siblings().removeClass('highlighted');
				$(event.target).removeClass('highlighted');
				$(event.target).addClass('highlighted');
				$(event.target).prevAll().addClass('highlighted');
                            })
                            .on('mouseout', '[class^="rating-"]', function (event) {
                                var ratingId = this.id.split('_');
                                if (!$('input[id^=' + ratingId[0] + '_]:checked').val()) {
                                    $('#rating-name-' + ratingId[1]).text('');
				    $(event.target).siblings().removeClass('highlighted');
				    $(event.target).removeClass('highlighted');
                                } else {
                                    var checkedId = $('input[id^=' + ratingId[0] + '_]:checked').attr('id').split('_');
                                    var ratingName = $('#' + checkedId[0] + '_' + ratingId[1] + '_' + checkedId[1] + '_label').attr('title');
                                    $('#rating-name-' + ratingId[1]).text(ratingName);
				    $('[class^="rating-"]').removeClass('highlighted');
				    console.log(checkedId[1]);
				    $('.rating-' + checkedId[1]).prevAll().addClass('highlighted');
				    $('.rating-' + checkedId[1]).addClass('highlighted');
                                }
                            });
                    });
                });
            </script>
            <script type="text/x-magento-init">
            {
                "[data-role=product-review-form]": {
                    "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
                }
            }
            </script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?php echo __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>


