
<?php
$_product = $block->getCurrentProduct();
$medias = $_product->getMediaGalleryImages()->getItems();

function filter($media) {
    if ($media->getMediaType() == "external-video") {
        return 1;
    }
    return 0;
}

$videos = array_filter($medias, "filter");
?>

<?php if (count($videos) > 0): ?>
    <div class="block block-product-video">
        <div class="block-title title">
            <strong role="heading" aria-level="2"><?php echo __('Related Video Shorts') ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($videos as $video ): ?>
                <div class="video-content">
                    <div class="video-image">
                        <a href="<?php echo $video->getVideoUrl();?>" target=_blank><img src="<?php echo $video->getUrl();?>"></a>
                    </div>
                    <div class="video-title">
                        <span><?php echo $video->getVideoTitle();?></span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>