<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageTitle())) {
    $title = '<strong class="" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageTitle()) . '</strong>';
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?php echo $cssClass; ?>">
    <div class="container">
		
		<?php if ($block->escapeHtml($block->getRequest()->getFullActionName()) == 'checkout_cart_index'): ?>
			<h2 class="page-title"
				<?php if ($block->getId()): ?> id="<?php echo $block->getId();?>" <?php endif; ?>
				<?php if ($block->getAddBaseAttributeAria()): ?>
					aria-labelledby="<?php echo $block->getAddBaseAttributeAria(); ?>"
				<?php endif; ?>>
				<?php echo $title ?> 
		</h2>
        <?php elseif ($block->escapeHtml($block->getRequest()->getFullActionName()) == 'sales_order_view'):?>
            <h2 class="page-title"
                <?php if ($block->getId()): ?> id="<?php echo $block->getId();?>" <?php endif; ?>
                <?php if ($block->getAddBaseAttributeAria()): ?>
                    aria-labelledby="<?php echo $block->getAddBaseAttributeAria(); ?>"
                <?php endif; ?>>
                <?php echo $block->escapeHtml("My Account") ?>
            </h2>
		<?php else: ?>
		<div class="other-header">
				<h1 <?php if ($block->getId()): ?> id="<?php echo $block->getId();?>" <?php endif; ?>
				<?php if ($block->getAddBaseAttributeAria()): ?>
					aria-labelledby="<?php echo $block->getAddBaseAttributeAria(); ?>"
				<?php endif; ?>><?php echo $block->escapeHtml($block->getPageTitle()) ?></h1>
			</div>
			
		<?php endif; ?>
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
<?php endif; ?>
