<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" class="heading-3" role="heading" aria-level="2"><?php echo __('New Customers') ?></strong>
    </div>
    <div class="block__content" aria-labelledby="block-new-customer-heading">
        <p><?php echo __('Creating an account has many benefits:') ?></p>
		<h5><?php echo __('ORDER TRACKING') ?></h5>
		<p><?php echo __('Track or check the status of pending orders and view your past orders.') ?></p>
		<h5><?php echo __('ORDER FASTER') ?></h5>
		<p><?php echo __('Save time when placing your next order by using your saved your shipping address 
and payment information.') ?></p>
		<h5><?php echo __('Add to wishlist') ?></h5>
		<p><?php echo __('Browse the site and add items to your “wishlist” list to conveniently add to your 
shopping cart when you’re ready to purchase.') ?></p>
		<p><?php echo __('and more...') ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php echo $block->getCreateAccountUrl() ?>" class="action create primary"><span><?php echo __('Create an Account') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
