<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter filter-wrapper" id="layered-filter-block" >
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <?php $wrapOptions = false; ?>
        <?php foreach ($block->getFilters() as $filter): ?>
        <?php if ($filter->getItemsCount()): ?>

        <?php if (!$wrapOptions): ?>
			<button type="button" class="action filter-toggle"> <span><?php echo __('Refine your search'); ?> <i class="fa fa-angle-right" aria-hidden="true"></i></span></button>
            <ul class="layered-menu">
                <?php  $wrapOptions = true; endif; ?>
                    <li class="layered-menu-option">
                        <div class="tab-handle">
                            <?php echo __($filter->getName()) ?>                        
                        </div>
                        <?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>                       
                    </li>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>                
            </ul>
            <div style="clear:both"></div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
        <?php endif; ?>
        <div class="block-content filter-content">
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="filter-current--wrapper">
                    <span>filter icon</span>
                    <?php echo $block->getChildHtml('state') ?>
                    <div class="block-actions filter-actions">
                        <a href="<?php /* @escapeNotVerified */
                        echo $block->getClearUrl() ?>"
                           class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                                echo __('Clear All') ?></span></a>
                    </div>
                    
                </div>
            <?php endif; ?>

    
            <?php $accItems = 0; $openItems = '0'; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php $accItems++; ?>
                <?php $openItems .= ' '. $accItems; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            ".filter-content": {
                "Magento_LayeredNavigation/js/modal-filter": {}
            }
        }
    </script>
    <script>
        require(["jquery"],function($){
            $(document).ready(function(){                                
                $('.tab-handle').on('click',function(){                                                                        
                    if($(this).hasClass("selected")){    
                        $(this).removeClass("selected");       
                        $(this).siblings('.attributes').addClass("hidden");             
                    }else{
                        $('.tab-handle').removeClass("selected");
                        $(this).addClass("selected");
                        $('.tab-handle').siblings('.attributes').addClass("hidden");
                        $(this).siblings('.attributes').removeClass("hidden");
                    }                    
                    
                });
		$('.filter-toggle').on('click',function() {
                        if($('.layered-menu').is(":visible")){
                            $('.layered-menu').hide();    
                        }else{
                            $('.layered-menu').show();
                 	}
                });
            })
        })
    </script>

<?php endif; ?>
