.post-items {
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    display: flex;
    flex-wrap: wrap;
    margin: 0 -15px;
}
#post-carousel {
    margin: 0;
    
}
#post-carousel .post-item {
    position: relative;
}

.post-items .post-item {
    padding: 0 15px;
    box-sizing: border-box;
    margin-bottom: 30px;
    white-space: normal;

}
.post-items-carousel .post-title a { color: #fff;  }
.post-items-carousel .post-link,
.post-items-carousel .post-short-content { color: #fff; font-size: 14px; margin-bottom: 0;}
.post-items-carousel .post-short-content p { margin-bottom: 0;}
.post-items-carousel .post-link {text-decoration: underline; margin-bottom: 7px;}
.post-items-carousel .post-data a,
.post-items-carousel .post-data{color: #fff; font-size: 13px;}
.post-items-carousel .post-data{margin-top: 7px;}
.post-items-carousel .post-item .content-wrapper{
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    padding: 15px;
    background: rgba(0, 0, 0, 0.6);
    color: #ddd;
    max-height: 50%;
    }

.post-items.items-1 .post-item{
    -moz-flex-basis: 100%;
    -ms-flex-basis: 100%;
    flex-basis: 100%;
    width:100%;
}

.post-items.items-2 .post-item{
    -moz-flex-basis: 50%;
    -ms-flex-basis: 50%;
    flex-basis: 50%;
    width:50%;
}

.post-items.items-3 .post-item{
    -moz-flex-basis: 33.3333%;
    -ms-flex-basis: 33.3333%;
    flex-basis: 33.3333%;
    width:33.3333%;
}

.post-items.items-4 .post-item{
    -moz-flex-basis: 25%;
    -ms-flex-basis: 25%;
    flex-basis: 25%;
    width:25%;
}