<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary<?php echo !$rating ? ' no-rating' : ''?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if ($rating):?>
    <div class="rating-summary">
         <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
         <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $rating; ?>%">
             <meta itemprop="worstRating" content = "1"/>
             <meta itemprop="bestRating" content = "100"/>
             <meta itemprop="ratingValue" content = "<?php /* @escapeNotVerified */ echo $rating ?>"/>
             <div class="rating-result__stars">
                 <?php
                 $half_star_id = round( (int)$rating / 20 );
                 for($i = 0; $i < 5; $i++){
                     echo '<span class="icon-star"></span>';
                 } ?>
             </div>

             <div class="rating-result__text">
                 <div style="width:<?php /* @escapeNotVerified */ echo $rating; ?>%">
                     <?php
                     for($i = 0; $i < 5; $i++){
                         echo '<span class="icon-star"></span>';
                     } ?>
                 </div>
             </div>

         </div>
     </div>
    <?php endif;?>
    <div class="reviews-actions">
        <a class="view" href="<?php /* @escapeNotVerified */ echo $url ?>"><span itemprop="reviewCount"><?php /* @escapeNotVerified */ echo $block->getReviewsCount() ?></span>&nbsp;<span><?php /* @escapeNotVerified */ echo($block->getReviewsCount() == 1) ? __('Review') : __('Reviews') ?></span></a>
        <a class="add" href="<?php /* @escapeNotVerified */ echo $urlForm ?>"><?php /* @escapeNotVerified */ echo __('Add Your Review') ?></a>
    </div>
</div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
<div class="product-reviews-summary empty">
    <div class="reviews-actions">
        <a class="action add" href="<?php /* @escapeNotVerified */ echo $urlForm; ?>">
            <?php /* @escapeNotVerified */ echo __('Be the first to review this product') ?>
        </a>
    </div>
</div>
<?php endif; ?>
