<div class="admin__field">
    <label for="invoice_comment_text" class="admin__field-label">
        <span><?php /* @escapeNotVerified */ echo __($block->getElement()->getLabel()) ?></span>
    </label>
    <div class="admin__field-control">
        <?php
        echo $block->getChildHtml('slideritem.image.buttonlayer');
        echo $block->getChildHtml('slideritem.text.buttonlayer');
        echo $block->getChildHtml('slideritem.image.buttonlayer.duplicate');
        echo $block->getChildHtml('slideritem.image.buttonlayer.update');
        echo $block->getChildHtml('slideritem.image.buttonlayer.remove');
        echo $block->getChildHtml('slideritem.image.buttonlayer.remove.all');
        ?>
    </div>
</div>
