<?php /** @var TemplateMonster\SocialSharing\Block\AddThis\Icons $block */ ?>
<div class="addthis_toolbox addthis_default_style" <?php echo $block->getCustomMetadata() ?>>
    <a class="addthis_button_preferred_1"></a>
    <a class="addthis_button_preferred_2"></a>
    <a class="addthis_button_preferred_3"></a>
    <a class="addthis_button_preferred_4"></a>
    <a class="addthis_button_preferred_5"></a>
    <a class="addthis_button_compact" href="javascript:void(0)"></a>
</div>