<?php /**   */ ?>
<?php
$optionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
?>
/*************** Primary Color  ***************/

/* background Primary */
.actions-primary .action,
.primary .action,
.action.primary,
.checkout.methods .action,
.slider-pro-wrapper .link-slider,
.custom-item-2 .link-button,
.custom-item-3 .link-custom,
.parallax-container .link-parallax,
.rd-navbar-cart-toggle .counter,
.slider-pro-wrapper .sp-buttons .sp-button.sp-selected-button,
.slider-pro-wrapper .sp-buttons .sp-button::before,
.layout_1 .block-newsletter,
.layout_2 .block-newsletter,
.opc-progress-bar .opc-progress-bar-item._active::after,
.opc-progress-bar .opc-progress-bar-item._active span::after,
.support-page .boxes-block li div:hover,
.faq-page #faq-accordion .accordion-trigger::before,
.modal-popup .modal-footer button,
.scrollToTop:hover,
.items.methods .action.multicheckout span::after,
.item-options .action.multicheckout span::after,
.box-actions a.action.change-password,
.mm-label.new,
.custom-item-1 .link-button:hover,
.custom-item-5 .link-custom,
.custom-item-4.extra .link-custom,
.custom-item-6 .link-custom,
.buttons-container .subscribe,
.not-found-page .not-found-page_bottom dd a,
.block-newsletter.block .primary,
.custom-item-12 .link-custom,
.sm-content .sm-button,
.category-list .category-button,
.custom-item-14 .link-custom,
.custom-item-15 .link-custom,
.sidebar .block.block-bg_2-custom,
.custom-item-17 .link-custom,
.custom-item-19 .link-custom,
.custom-item-22,
.custom-item-8 .link-custom:hover,
.custom-item-26 .block-bg_2-custom,
.static-link-slider:hover,
.custom-item-27 .link-custom:hover,
.custom-item-27 .item-extra-2 .link-custom,
.custom-item-28 .link-custom:hover,
.custom-item-28 .item-extra-2 .link-custom,
.sidebar .price-slider .ui-slider-range,
.ui-slider-handle,
.filter-options-content .price-slider .slider-fields a.action,
.smart-labels .sale.label-text,
.listing-gallery .fotorama__arr .fotorama__arr__arr,
.page-product-bundle #bundle-slide,
.modal-popup.quick-view #bundle-slide,
.block.discount .apply,
.checkout-onepage-success #registration .action.primary{
<?php if ($optionsHelper->getPrimaryColor()): ?>
    background-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
    border-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}


@media (min-width: 768px) {
.layout_4 .rd-navbar-toggle{
<?php if ($optionsHelper->getPrimaryColor()): ?>
    background-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
    border-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}
}

/* Border Primary */
.gallery-placeholder .fotorama__thumb-border,
.fotorama-item .fotorama__thumb-border,
.opc-progress-bar .opc-progress-bar-item._active::before,
.support-page .boxes-block li div,
#page-preloader .spinner:before,
#page-preloader .spinner:after,
.loading-mask .loader:before,
.loading-mask .loader:after,
.checkout-index-index .loading-mask .loader::before,
.checkout-index-index .loading-mask .loader::after,
table .table-bordered,
.big-circle-icon,
.custom-item-1 .link-button,
.layout_4 .rd-navbar-search .form-group,
.custom-item-7 .extra-position .link-custom,
.layout_3 .block-newsletter .primary.subscribe {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    border-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}


/* Color Primary */
mark,
em,
.field.choice input[type="checkbox"] + .label::before,
.field.choice input[type="radio"] + .label::before,
.rd-navbar-static .rd-navbar-collapse a,
.custom-item-1.extra .title-1,
.header-info i,
.price,
.products .product-item .reviews-actions .view,
.custom-item-3 .title-1,
.widget.blog-posts .post-data .create-date time,
.widget.blog-posts .post-items .post-data .post-comments a,
.widget.blog-posts .post-data .post-author span,
.footer .footer-col-content li a,
.rd-navbar-cart .block-content > .actions .secondary .primary,
.breadcrumbs .items .item strong,
.rd-navbar-static .rd-navbar-nav > li.active > a,
.modes .modes-mode.active,
.catalog-product-view .product-info-stock-sku .stock,
.catalog-product-view .reviews-actions a,
.catalog-product-view .data.items .title.active a,
.block.related .block-actions button.action.select,
.field.choice input[type="checkbox"] + .label::before,
.field.choice input[type="radio"] + .label::before,
.block-posts-list .post-items .post-data .post-author span,
.block-posts-list .post-items .post-data .create-date time,
.block-posts-list .post-items .post-data .post-comments a,
.post-page .post-data .post-author span,
.post-page .post-data .create-date time,
.post-page .post-data .post-comments a,
.customer-service .list-block h4::before,
.about-us-page ul a,
.shipping-delivery-page .shipping-delivery-page_shipping-icon::before,
.shipping-delivery-page .shipping-delivery-page_track-icon::before,
.shipping-delivery-page .shipping-delivery-page_order-icon::before,
.secure-payment-page h4::before,
.secure-payment-page .secure-payment_icons ul a,
.support-page .boxes-block li div span::before,
.guarantee-page h4::before,
.terms-conditions-page ul h4::before,
.faq-page #faq-accordion .accordion-content p::before,
.account-nav .item.current,
.items.methods .action.multicheckout,
.item-options .action.multicheckout,
.cart-container .main.actions .action span,
.filter-options-content .item a:hover,
.customer-account-index .account-nav .nav.items strong,
.page-title-wrapper .order-date,
.account-nav .item.current a,
.opc-sidebar .table-totals th,
.opc-sidebar .table-totals td,
.opc-estimated-wrapper .minicart-wrapper button,
.big-circle-icon:before,
.primary-color,
.filter-current--wrapper .filter-actions .action,
.custom-item-4 .link-custom,
.custom-item-5 .title-1,
.modal-popup.newsletter-popup .closeText:hover,
.grid-left-fixed .close:hover,
.sidebar .block .block-title.left-custom-title span,
.opc-wrapper .field-tooltip .field-tooltip-action::before,
.custom-item-9 .link-custom,
.custom-item-10 .link-custom,
.custom-item-11.extra-color .title-1,
.custom-item-13 span,
#sm-timer,
.custom-item-16 .link-custom,
.custom-item-25 .desc-1,
.custom-item-26 .left-custom-title span,
.rd-navbar-static .layout_5 .rd-navbar-nav > li > a,
.layout_5 .block-newsletter #newsletter,
.layout_5 .block-newsletter .control::before {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}

/* Hover Primary */
a:hover,
.rd-navbar-static .rd-navbar-nav > li.parent li.focus > a,
.rd-navbar-static .rd-navbar-nav > li.parent li.opened > a,
.rd-navbar-static .rd-navbar-nav > li.parent a:hover,
.account-nav a:hover,
.header-switchers .actions .action.active,
.header-switchers .actions .action:hover,
.rd-navbar-search-toggle:hover,
.modes .modes-mode:hover,
.modes .modes-mode.active,
.catalog-product-view .product-social-links .action:hover,
.switcher .dropdown .mage-dropdown-dialog a:hover,
.pages .item .next:hover,
.pages .item .previous:hover,
.pages .item .next:hover span:before,
.pages .item .previous:hover span:before,
.widget.blog-posts .post-items .post-title h3 a:hover,
.rd-navbar-fixed .rd-navbar-nav li.opened > a,
.rd-navbar-fixed .rd-navbar-nav li a:hover,
.rd-navbar-fixed .rd-navbar-nav li.active > a,
.block-posts-list .post-items .post-title h3 a:hover,
a.action.delete:hover,
a.action.edit:hover,
a.action.change-password:hover,
.checkout-index-index .checkout-container .authentication-wrapper button.action-auth-toggle:hover,
.checkout-index-index .checkout-container .authentication-wrapper .secondary a:hover,
h1 a:hover,
.heading-1 a:hover,
h3 a:hover,
.heading-3 a:hover,
.collapsible-block .opener a:hover,
h4 a:hover,
.heading-4 a:hover,
.filter-current .filter-current-subtitle a:hover,
.opc-block-shipping-information .shipping-information-title a:hover,
.review-list .review-title a:hover,
.review-add .review-legend a:hover,
h5 a:hover,
.heading-5 a:hover,
h6 a:hover,
.heading-6 a:hover,
.select2-results__option[aria-selected]:hover,
.minicart-items .details-qty .update-cart-item:hover,
.close.subscribe:hover,
.header-info a:hover,
.block.featured[role="tablist"] .page-title:hover,
.block.featured[role="tablist"] .page-title.active{
<?php if ($optionsHelper->getPrimaryColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}

@media (min-width: 768px) {
.layout_2 .footer .footer-col:not(.footer-info) a:hover  {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}
}
/* =============================================== */
/*************** Default Color  ***************/
input[type="text"],
.input-text, input[type="email"],
input[type="password"],
input[type="number"],
select,
textarea,
.footer .list-contacts-footer li a,
.footer .list-footer li a,
.footer .list-icon li a,
.action.tocompare,
.action.towishlist,
.pages .item .page,
.filter-options-content .item a,
.modes a,
.toolbar-sorter a,
.swatch-option.text,
.catalog-product-view .product-social-links .action,
.review-fieldset .review-legend strong,
.review-field-rating > label.label,
.old-price .price,
.rd-navbar-static .rd-navbar-collapse li a::before,
.rd-navbar-cart-toggle span::before,
.rd-navbar-cart-toggle span::after,
.switcher .dropdown .mage-dropdown-dialog a,
a.action.delete,
a.action.edit,
a.action.change-password,
.pages .item.pages-item-previous span::before,
.pages .item.pages-item-next span::before,
.customer-account-index .account-nav .nav.items a,
.account-nav a,
.widget.blog-posts .post-items .post-item .post-data > span::before,
.block-compare .action.delete,
.footer h4::after,
.block-posts-list .post-items .post-data .create-date a span::before,
.block-posts-list .post-items .post-data .create-date::before,
.block-posts-list .post-items .post-data .post-author a span::before,
.block-posts-list .post-items .post-data .post-author::before,
.block-posts-list .post-items .post-data .post-comments a span::before,
.block-posts-list .post-items .post-data .post-comments::before,
.post-page .post-data .create-date a span::before,
.post-page .post-data .create-date::before,
.post-page .post-data .post-author a span::before,
.post-page .post-data .post-author::before,
.post-page .post-data .post-comments a span::before,
.post-page .post-data .post-comments::before,
.cart-container .main.actions .action::before,
.cart-container .main.actions .action:hover,
.cart-container .main.actions .action:hover span,
.cart-summary #co-shipping-method-form .label,
#cart-totals .table.totals .shipping .value,
.opc-sidebar .opc-block-summary .table-totals th .value,
.opc-sidebar .opc-block-summary .table-totals td .value,
.control.review-control-vote label[class^='rating-'],
.search-terms ul a,
.header-info a,
.filter-options-title::before,
.filter-options-content .count,
.contact-index-index legend.legend .note,
.custom-item-11.extra-color .link-custom {
<?php if ($optionsHelper->getPrimaryFontColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
<?php endif; ?>
}

.opc-progress-bar .opc-progress-bar-item::before {
<?php if ($optionsHelper->getPrimaryFontColor()): ?>
    border-color: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
<?php endif; ?>
}

.opc-progress-bar .opc-progress-bar-item span::after {
<?php if ($optionsHelper->getPrimaryFontColor()): ?>
    background: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
<?php endif; ?>
}
/* ================================================== */
/*************** Link Color (Primary)  ***************/
/****** Link Color  ***/
a,
.widget.blog-posts .post-items .post-title h3 a,
.footer .footer-col-content li a:hover,
.footer .list-footer li a:hover,
.widget.blog-posts .owl-controls .owl-prev:hover::before,
.widget.blog-posts .owl-controls .owl-next:hover::before,
.products .product-item .actions-secondary .action:hover,
.toolbar-sorter a:hover,
.rd-navbar-static .rd-navbar-collapse a:hover::before,
.rd-navbar-static .rd-navbar-collapse a:hover,
.rd-navbar-search-toggle,
.faq-page #faq-accordion .accordion-trigger span,
.products-grid.wishlist a.action.delete:hover,
.products-grid.wishlist a.action.edit:hover,
.rd-navbar-cart-toggle span,
.block-wishlist .actions-secondary .btn-remove:hover,
.block-compare .action.delete:hover,
.widget.blog-posts .post-items .post-data .post-comments a:hover,
.block-posts-list .post-items .post-title h3 a,
.block-posts-list .post-items .post-data .create-date a:hover,
.block-posts-list .post-items .post-data .post-author a:hover,
.block-posts-list .post-items .post-data .post-comments a:hover,
.mm-label,
.items.methods .action.multicheckout:hover,
.item-options .action.multicheckout:hover,
.opc-sidebar .items-in-cart .product-item-name,
.opc-sidebar .items-in-cart .details-qty,
.rd-navbar-cart .block-content > .actions .secondary .primary:hover,
.products .product-item .reviews-actions .view:hover,
.filter-current--wrapper .filter-actions .action:hover,
.custom-item-1 .link-button,
.custom-item-3 .link-custom:hover,
.minicart-items .product.options .toggle,
.secure-payment-page .secure-payment_icons ul a:hover,
.owl-controls .owl-prev:hover,
.owl-controls .owl-next:hover,
.block.discount:hover,
.cart-summary .title:hover,
.items.methods .action.multicheckout:hover,
.item-options .action.multicheckout:hover,
.items.methods .action.multicheckout:hover span:after,
.item-options .action.multicheckout:hover span:after,
.opc-progress-bar .opc-progress-bar-item span,
.rd-navbar-cart .block-minicart .empty,
.about-us-page ul a:hover,
.shipping-delivery-page ul li:before,
.owl-controls .owl-prev:before,
.owl-controls .owl-next:before,
.rd-navbar-cart-toggle:not(.active) .counter.empty,
.custom-item-4 .link-custom:hover,
.table-comparison .action.towishlist:hover,
.catalog-product-view .reviews-actions a:hover,
.grid-left-fixed .close,
.layout_3 .filter-toggle-full,
.custom-item-9 .link-custom:hover,
.custom-item-10 .link-custom:hover,
.custom-item-16 .link-custom:hover,
.layout_3 .block-newsletter .primary.subscribe,
.custom-item-27 .item-extra-2 .link-custom:hover {
<?php if ($optionsHelper->getPrimaryLinkColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
<?php endif; ?>
}



@media screen and (max-width: 768px) {
.collapsible-block .opener {
<?php if ($optionsHelper->getPrimaryLinkColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
<?php endif; ?>
}
}


@media screen and (max-width: 768px) {
.rd-navbar-search-toggle {
<?php if ($optionsHelper->getPrimaryFontColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
<?php endif; ?>
}
}

@media (min-width: 768px) {
.layout_2 .footer .footer-col:not(.footer-info) a  {
<?php if ($optionsHelper->getPrimaryLinkColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
<?php endif; ?>
}
}
/****** background Color  ***/
.rd-navbar-static .rd-navbar-nav > li > a::after,
.footer .list-icon li a:hover,
.widget.blog-posts .post-items .post-button:hover,
.widget.featured .product-item .product-label,
.slider-pro-wrapper .sp-buttons .sp-button,
.actions-primary .action:hover,
.primary .action:hover,
.action.primary:hover,
.checkout.methods .primary:hover,
.pages .item.current .page,
.pages .item .page:hover,
.actions .action:hover,
.actions-toolbar .action:hover,
.box-actions .action:hover,
.product-item-actions .action:hover,
.checkout.methods .action:hover,
.rd-navbar-cart-toggle.active .counter,
.rd-navbar-cart-toggle:hover .counter,
.box-actions a.action.change-password:hover,
.slider-pro-wrapper .link-slider:hover,
.slider-pro-wrapper .button-slider.extra .link-slider:hover,
.parallax-container .link-parallax:hover,
.action.filter-toggle:hover,
.block-posts-list .post-items a.post-link:hover,
.items.methods .action.multicheckout:hover span::after,
.item-options .action.multicheckout:hover span::after,
.custom-item-2 .link-button:hover,
.custom-item-5 .link-custom:hover,
.custom-item-4.extra .link-custom:hover,
.custom-item-6 .link-custom:hover,
.modal-popup .modal-footer button:hover,
.buttons-container .subscribe:hover,
.not-found-page .not-found-page_bottom dd a:hover,
.layout_3 .filter-toggle-full:hover,
.block-newsletter.block .primary:hover,
.custom-item-7 .link-custom:hover,
.custom-item-12 .link-custom:hover,
.sm-content .sm-button:hover,
.category-list .category-button:hover,
.custom-item-14 .link-custom:hover,
.custom-item-15 .link-custom:hover,
.custom-item-17 .link-custom:hover,
.custom-item-21 .link-custom:hover,
.custom-item-19 .link-custom:hover,
.layout_3 .block-newsletter .primary.subscribe:hover,
.layout_5 .block-newsletter .primary.subscribe:hover,
.slider-content-static .static-link-slider:hover,
.slider-content-static-2 .static-link-slider:hover,
.custom-item-27 .item-extra-2 .link-custom:hover,
.custom-item-28 .item-extra-2 .link-custom:hover,
.filter-options-content .price-slider .slider-fields a.action:hover,
.smart-labels .label-text,
.page-product-bundle #bundle-slide:hover,
.modal-popup.quick-view #bundle-slide:hover,
.block.discount .apply:hover,
.checkout-onepage-success #registration .action.primary:hover {
<?php if ($optionsHelper->getPrimaryLinkColor()): ?>
    background-color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
<?php endif; ?>
}


/****** Border Color  ***/
.footer .list-icon li a:hover,
.widget.blog-posts .post-items .post-button:hover,
.actions-primary .action:hover,
.primary .action:hover,
.action.primary:hover,
.checkout.methods .primary:hover,
.actions .action:hover,
.actions-toolbar .action:hover,
.box-actions .action:hover,
.product-item-actions .action:hover,
.checkout.methods .action:hover,
.box-actions a.action.change-password:hover,
.slider-pro-wrapper .link-slider:hover,
.parallax-container .link-parallax:hover,
.action.filter-toggle:hover,
.block-posts-list .post-items a.post-link:hover,
.custom-item-2 .link-button:hover,
.custom-item-1 .link-button,
.custom-item-5 .link-custom:hover,
.custom-item-4.extra .link-custom:hover,
.custom-item-6 .link-custom:hover,
.modal-popup .modal-footer button:hover,
.buttons-container .subscribe:hover,
.layout_3 .filter-toggle-full:hover,
.block-newsletter.block .primary:hover,
.custom-item-7 .link-custom:hover,
.custom-item-12 .link-custom:hover,
.sm-content .sm-button:hover,
.category-list .category-button:hover,
.custom-item-14 .link-custom:hover,
.custom-item-15 .link-custom:hover,
.custom-item-17 .link-custom:hover,
.custom-item-19 .link-custom:hover,
.custom-item-21 .link-custom:hover,
.layout_3 .block-newsletter .primary.subscribe:hover,
.layout_2 .block-newsletter .primary.subscribe:hover,
.layout_1 .block-newsletter .primary.subscribe:hover,
.layout_5 .block-newsletter .primary.subscribe:hover,
.slider-content-static .static-link-slider:hover,
.slider-content-static-2 .static-link-slider:hover,
.custom-item-27 .item-extra-2 .link-custom:hover,
.custom-item-28 .item-extra-2 .link-custom:hover,
.filter-options-content .price-slider .slider-fields a.action:hover,
.page-product-bundle #bundle-slide:hover,
.modal-popup.quick-view #bundle-slide:hover,
.checkout-onepage-success #registration .action.primary:hover {
<?php if ($optionsHelper->getPrimaryLinkColor()): ?>
    border-color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
<?php endif; ?>
}

/* =============================================== */
/*************** Secondary ************************/

/****** Secondary Color ******/
.special-price .price,
.products .product-item .actions-primary .unavailable,
.rd-navbar-static .layout_5 .rd-navbar-nav > li.parent li > a::before {
<?php if ($optionsHelper->getSecondaryColor()): ?>
    color: <?php echo $optionsHelper->getSecondaryColor(); ?>;
<?php endif; ?>
}
/****** Secondary Background ******/
.timer-wrapper,
.widget.featured .product-item .product-label.Sale,
.mm-label.hot,
.layout_5 .rd-navbar-nav > li > a::after,
.layout_5 .block-newsletter {
<?php if ($optionsHelper->getSecondaryColor()): ?>
    background-color: <?php echo $optionsHelper->getSecondaryColor(); ?>;
<?php endif; ?>
}

.slider-content-static .static-link-slider,
.slider-content-static-2 .static-link-slider,
[class*='parallax_layout_5'] .link-parallax {
<?php if ($optionsHelper->getSecondaryColor()): ?>
    background-color: <?php echo $optionsHelper->getSecondaryColor(); ?>;
    border-color: <?php echo $optionsHelper->getSecondaryColor(); ?>;
<?php endif; ?>
}

/* =============================================== */
/*************** Title primary color  ************************/
h1,
h2,
h3,
h4,
h5,
h6,
.heading-1,
.heading-2,
.heading-3,
.heading-4,
.heading-5,
.heading-6,
table.table thead th,
table.table th,
.custom-item-1.extra .desc-1,
.cms-page-view h1 span,
.cms-page-view heading-1 span,
.field .label,
.field label,
.search.advanced legend.legend,
.block-title,
.cart-summary > .title,
.block-subtitle,
.block-content .subtitle,
.cart-summary #co-shipping-method-form .item-title,
.cart-summary #co-shipping-method-form .field.choice input[type="radio"] + .label::before,
.cart-summary .title,
#cart-totals .table.totals .mark,
.post-comments-block .comment-info .post-data,
.filter-options-title,
.review-add .review-legend,
.catalog-product-view .review-list .review-details,
.catalog-product-view .review-list .review-title,
.catalog-product-view .product-options-wrapper .swatch-attribute-label,
.form.friend .legend,
.box-title,
table.table .col.name .product-item-name,
.order-links,
.page-title-wrapper .order-status,
.account .legend,
.panel-container-wrap .welcome,
.custom-item-3 .desc-1,
.custom-item-2 .desc-1,
.custom-item-2 .title-1,
.cart-summary  .field.choice input[type=radio] + .label:before,
.custom-item-4:not(.extra) .title-1,
.custom-item-5 .banner-label,
.opc-sidebar .opc-block-summary span.title,
.opc-sidebar .shipping-information-title,
.opc-sidebar .shipping-information-title strong,
.opc-sidebar .title,
.opc-sidebar .title strong,
.checkout-index-index .step-title,
.page-title-top,
.page-title,
.not-found-page,
.mm-text,
.message > div:after,
.contact-index-index legend.legend,
.layout_3 .block-newsletter .title strong,
.custom-item-9 .custom-item-content,
.custom-item-10 .title-1,
.custom-item-10 .desc-1,
.custom-item-11.extra-color .desc-1,
.custom-item-13 .title,
.category-list .category-name,
.custom-item-14 .custom-item-content,
.custom-item-15 .custom-item-content,
.custom-item-16 .custom-item-content,
.custom-item-17 .custom-item-content,
.custom-item-23 .title-static-block {
<?php if ($optionsHelper->getPrimaryTitleColor()): ?>
    color:<?php echo $optionsHelper->getPrimaryTitleColor(); ?>;
<?php endif; ?>
}

@media (max-width: 768px) {
.catalog-product-view .data.items .col.data::before {
<?php if ($optionsHelper->getPrimaryTitleColor()): ?>
    color:<?php echo $optionsHelper->getPrimaryTitleColor(); ?>;
<?php endif; ?>
}
}



/* ==================================================== */
/*************** Body Background ************************/

body {
<?php if ($optionsHelper->getBodyBackgroundColor()): ?>
    background-color: <?php echo $optionsHelper->getBodyBackgroundColor(); ?>;
<?php endif; ?>
<?php if ($optionsHelper->isBodyBackgroundImage()) : ?>
    background-image: <?php echo $optionsHelper->getBodyBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getBodyBackgroundImage() . ')' : 'none' ?>;
    background-size: <?php echo $optionsHelper->getBodyBackgroundImageSize(); ?>;
    background-attachment: <?php echo $optionsHelper->getBodyBackgroundImageAttachment(); ?>;
    background-position: <?php echo $optionsHelper->getBodyBackgroundImagePosition(); ?>;
    background-repeat: <?php echo $optionsHelper->getBodyBackgroundImageRepeat(); ?>;
<?php endif; ?>
<?php if ($optionsHelper->getPrimaryFontColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
<?php endif; ?>
}
<?php if ($optionsHelper->getBodyBackgroundColor()): ?>
    .widget.blog-posts .owl-carousel .owl-wrapper-outer::after,
    .products-grid .product-items:not(.owl-carousel)::before,
    .products-grid .product-items:not(.owl-carousel)::after {
    background-color: <?php echo $optionsHelper->getBodyBackgroundColor(); ?>;
    }
<?php endif; ?>
.layout_3 .block-newsletter {
<?php if ($optionsHelper->getBodyBackgroundColor()): ?>
    background-color: <?php echo $optionsHelper->getBodyBackgroundColor(); ?>;
<?php endif; ?>
}

/* ==================================================== */
/*************** Header Background ************************/

header.page-header,
.rd-navbar-static {
<?php if ($optionsHelper->getHeaderBackgroundColor()): ?>
    background-color: <?php echo $optionsHelper->getHeaderBackgroundColor(); ?>;
<?php endif; ?>
}
/* ====================================================== */
/*************** Footer Background ************************/

.page-footer{
<?php if ($optionsHelper->getFooterBackgroundColor()): ?>
    background-color: <?php echo $optionsHelper->getFooterBackgroundColor(); ?>;
<?php endif; ?>
<?php if ($optionsHelper->isFooterBackgroundImage()) : ?>
    background-image: <?php echo $optionsHelper->getFooterBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getFooterBackgroundImage() . ')' : 'none' ?>;
    background-size: <?php echo $optionsHelper->getFooterBackgroundImageSize(); ?>;
    background-attachment: <?php echo $optionsHelper->getFooterBackgroundImageAttachment(); ?>;
    background-position: <?php echo $optionsHelper->getFooterBackgroundImagePosition(); ?>;
    background-repeat: <?php echo $optionsHelper->getFooterBackgroundImageRepeat(); ?>;
<?php endif; ?>
}

/* ====================================================== */


<?php if($block->getWebsiteCode() == 'spare_parts'):  ?>
    .page-main .actions-primary .action,
    .page-main .primary .action,
    .page-main .action.primary,
    .custom-item-27 .item-extra-2 .link-custom{
    background-color:<?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
    border-color:<?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
    }
    .page-main .actions-primary .action:hover,
    .page-main .primary .action:hover,
    .page-main .action.primary:hover,
    .block-minicart .product-item-details .product.actions .action:hover{
    background-color:#fff;
    color:#000;
    }
    .product-social-links a:hover,
    .select2-results__option[aria-selected]:hover,
    .cart-table .actions .action:hover span,
    .filter-options-content .item a:hover,
    .comparison .delete:hover,
    .toolbar .modes .active {
    color:#000 !important;
    }
<?php endif;  ?>

@media (min-width: 768px) {
ul.social-links {
float: left;
clear: both;
width: 100%;
padding: 0!important;
text-align: left;
}
ul.social-links li {
display: inline-block;
}
}
@media (max-width: 768px) {
ul.social-links {
display: none;
}
}
